version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-fundicao
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./banco-de-dados:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  api:
    build:
      context: ./tool-system/tool-system  
      dockerfile: Dockerfile
    container_name: api-fundicao
    ports:
      - "5183:8080"
    volumes:
      - ./tool-system/tool-system/wwwroot:/app/wwwroot
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=fundicao;Uid=root;Pwd=root;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db 
  frontend:
    build:
      context: ./front-end
    ports:
      - "5173:5173"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    depends_on:
      - api
volumes:
  db_data: